# Generated by Django 3.0.14 on 2021-05-28 01:48

import core.models.core_tables
import core.models.custom_types
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='action_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('duration', models.FloatField(blank=True, db_column='duration', null=True)),
                ('repeating', models.IntegerField(blank=True, db_column='repeating', null=True)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
            ],
            options={
                'db_table': 'action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='action_def_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'action_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionParameter',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='parameter_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_description', models.CharField(blank=True, db_column='action_description', editable=False, max_length=255, null=True)),
                ('parameter_def_description', models.CharField(blank=True, db_column='parameter_def_description', editable=False, max_length=255, null=True)),
                ('parameter_val_nominal', core.models.custom_types.ValField(blank=True, db_column='parameter_val', max_length=255, null=True)),
                ('parameter_val_actual', core.models.custom_types.ValField(blank=True, db_column='parameter_val_actual', max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_action_parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionParameterDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='action_parameter_def_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', editable=False, max_length=255, null=True)),
                ('parameter_description', models.CharField(blank=True, db_column='parameter_description', editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'action_parameter_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionParameterDefAssign',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='action_parameter_def_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vw_action_parameter_def_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='actor_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActorPref',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='actor_pref_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pkey', models.CharField(blank=True, max_length=255, null=True)),
                ('pvalue', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actor_pref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='bom_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BomCompositeMaterial',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='bom_material_composite_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bom_material_composite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BomMaterial',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='bom_material_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('alloc_amt_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
                ('used_amt_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
                ('putback_amt_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bom_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='calculation_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('in_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
                ('in_opt_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
                ('out_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
                ('calculation_alias_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calc_definition', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
            ],
            options={
                'db_table': 'vw_calculation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='calculation_def_uuid', primary_key=True, serialize=False)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calc_definition', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
            ],
            options={
                'db_table': 'vw_calculation_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationParameterDefAssign',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='calculation_parameter_def_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vw_calculation_parameter_def_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompositeMaterial',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_composite_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('addressable', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_composite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompositeMaterialProperty',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_composite_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('composite_class', models.CharField(choices=[('template', 'template'), ('model', 'model'), ('object', 'object')], editable=False, max_length=64)),
                ('composite_material_description', models.CharField(blank=True, db_column='composite_description', editable=False, max_length=255, null=True)),
                ('component_class', models.CharField(choices=[('template', 'template'), ('model', 'model'), ('object', 'object')], editable=False, max_length=64)),
                ('property_class', models.CharField(choices=[('nominal', 'nominal'), ('actual', 'actual')], max_length=64)),
                ('property_def_class', models.CharField(choices=[('intrinsic', 'intrinsic'), ('extrinsic', 'extrinsic')], editable=False, max_length=64)),
                ('property_description', models.CharField(blank=True, db_column='property_description', editable=False, max_length=255, null=True)),
                ('property_short_description', models.CharField(blank=True, db_column='property_short_description', editable=False, max_length=255, null=True)),
                ('value', core.models.custom_types.ValField(blank=True, db_column='property_value_val', max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_material_composite_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='condition_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('condition_description', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('calculation_description', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('in_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
                ('out_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionCalculationDefAssign',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='condition_calculation_def_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vw_condition_calculation_def_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='condition_def_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'condition_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionPath',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='condition_path_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('condition_out_val', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'condition_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edocument',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='edocument_uuid', editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='title', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('filename', models.CharField(blank=True, db_column='filename', max_length=255, null=True)),
                ('source', models.CharField(blank=True, db_column='source', max_length=255, null=True)),
                ('edoc_type', models.CharField(blank=True, db_column='doc_type_description', max_length=255, null=True)),
                ('edocument', models.BinaryField(blank=True, null=True)),
                ('edoc_ver', models.CharField(blank=True, db_column='doc_ver', max_length=255, null=True)),
                ('ref_edocument_uuid', core.models.core_tables.RetUUIDField()),
            ],
            options={
                'db_table': 'vw_edocument',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdocumentX',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='edocument_x_uuid', editable=False, primary_key=True, serialize=False)),
                ('ref_edocument_uuid', core.models.core_tables.RetUUIDField()),
            ],
            options={
                'db_table': 'edocument_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='experiment_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_uid', models.CharField(db_column='ref_uid', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
            ],
            options={
                'db_table': 'experiment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentType',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='experiment_type_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=255)),
            ],
            options={
                'db_table': 'experiment_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentWorkflow',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='experiment_workflow_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('experiment_workflow_seq', models.IntegerField()),
            ],
            options={
                'db_table': 'experiment_workflow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='inventory_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryMaterial',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='inventory_material_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('part_no', models.CharField(blank=True, max_length=255, null=True)),
                ('onhand_amt', core.models.custom_types.ValField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialIdentifier',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_refname_uuid', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'material_refname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialIdentifierDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_refname_def_uuid', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'material_refname_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialIdentifierX',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_refname_x_uuid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'material_refname_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialProperty',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='property_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('material_class', models.CharField(choices=[('template', 'template'), ('model', 'model'), ('object', 'object')], editable=False, max_length=64)),
                ('description', models.CharField(blank=True, db_column='description', editable=False, max_length=255, null=True)),
                ('property_description', models.CharField(blank=True, db_column='property_description', editable=False, max_length=255, null=True)),
                ('property_short_description', models.CharField(blank=True, db_column='property_short_description', editable=False, max_length=255, null=True)),
                ('value', core.models.custom_types.ValField(blank=True, db_column='property_value_val', max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_material_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_type_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialTypeAssign',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_type_x_uuid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vw_material_type_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialTypeX',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_type_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'material_type_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='measure_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('measure_value', core.models.custom_types.ValField()),
            ],
            options={
                'db_table': 'measure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='measure_def_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('default_measure_value', core.models.custom_types.ValField(max_length=255)),
            ],
            options={
                'db_table': 'measure_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureType',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='measure_type_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'measure_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureX',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='measure_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_measure', core.models.core_tables.RetUUIDField(db_column='ref_measure_uuid')),
            ],
            options={
                'db_table': 'measure_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='note_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('notetext', models.TextField(blank=True, null=True, verbose_name='Note Text')),
                ('ref_note_uuid', core.models.core_tables.RetUUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteX',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='note_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_note', core.models.core_tables.RetUUIDField(db_column='ref_note_uuid')),
            ],
            options={
                'db_table': 'note_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='organization_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=3, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationTable',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='organization_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=3, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='outcome_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=255)),
            ],
            options={
                'db_table': 'outcome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='parameter_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parameter_val_nominal', core.models.custom_types.ValField(blank=True, db_column='parameter_val', max_length=255, null=True)),
                ('parameter_val_actual', core.models.custom_types.ValField(blank=True, db_column='parameter_val_actual', max_length=255, null=True)),
            ],
            options={
                'db_table': 'parameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='parameter_def_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('default_val', core.models.custom_types.ValField(db_column='default_val', max_length=255)),
                ('required', models.BooleanField()),
                ('unit_type', models.CharField(blank=True, db_column='parameter_def_unit_type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'parameter_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterX',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='parameter_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parameter_uuid', core.models.core_tables.RetUUIDField(db_column='parameter_uuid')),
                ('parameter_ref_uuid', core.models.core_tables.RetUUIDField(db_column='ref_parameter_uuid')),
            ],
            options={
                'db_table': 'parameter_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='person_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=3, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonTable',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='person_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state_province', models.CharField(blank=True, max_length=3, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='property_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('property_val', core.models.custom_types.ValField(blank=True, db_column='property_val', max_length=255, null=True)),
                ('property_class', models.CharField(choices=[('nominal', 'nominal'), ('actual', 'actual')], max_length=64)),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyDef',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='property_def_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('property_def_class', models.CharField(choices=[('intrinsic', 'intrinsic'), ('extrinsic', 'extrinsic')], max_length=64)),
                ('short_description', models.CharField(blank=True, db_column='short_description', max_length=255, null=True)),
                ('val_unit', models.CharField(blank=True, db_column='valunit', max_length=255, null=True)),
                ('unit_type', models.CharField(blank=True, db_column='property_def_unit_type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'property_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'property_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='status_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Systemtool',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='systemtool_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('systemtool_name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('ver', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'systemtool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemtoolType',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='systemtool_type_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'systemtool_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='tag_uuid', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_text', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('type_description', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagAssign',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='tag_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_tag', core.models.core_tables.RetUUIDField(db_column='ref_tag_uuid')),
            ],
            options={
                'db_table': 'vw_tag_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='tag_type_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_tag_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDef',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='type_def_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='category', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_type_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Udf',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='udf_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, null=True)),
                ('udf_value', core.models.custom_types.ValField(db_column='udf_val', max_length=255)),
                ('ref_udf', core.models.core_tables.RetUUIDField(db_column='ref_udf_uuid')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'udf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UdfDef',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='udf_def_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'udf_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UdfX',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='udf_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_uuid', core.models.core_tables.RetUUIDField(db_column='ref_udf_uuid')),
            ],
            options={
                'db_table': 'udf_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='workflow_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'workflow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionSet',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='workflow_action_set_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('repeating', models.BigIntegerField()),
                ('parameter_val_nominal', core.models.custom_types.CustomArrayField(base_field=core.models.custom_types.ValField(), blank=True, db_column='parameter_val', null=True, size=None)),
                ('source_material', django.contrib.postgres.fields.ArrayField(base_field=core.models.core_tables.RetUUIDField(blank=True, null=True), db_column='source_material_uuid', size=None)),
                ('destination_material', django.contrib.postgres.fields.ArrayField(base_field=core.models.core_tables.RetUUIDField(blank=True, null=True), db_column='destination_material_uuid', size=None)),
            ],
            options={
                'db_table': 'workflow_action_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowObject',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='workflow_object_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'workflow_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='workflow_step_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parent_path', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'db_table': 'workflow_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='workflow_type_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
            ],
            options={
                'db_table': 'workflow_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('standard_unit', models.CharField(blank=True, db_column='standard_unit', max_length=255, null=True)),
                ('allowed_units', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPassword',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('organization', models.OneToOneField(db_column='parent_uuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_password_organization', to='core.OrganizationTable')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('consumable', models.BooleanField(blank=True, null=True)),
                ('material_class', models.CharField(choices=[('template', 'template'), ('model', 'model'), ('object', 'object')], max_length=64)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_uuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='material_actor', to='core.Actor')),
                ('identifier', models.ManyToManyField(related_name='material_material_identifier', to='core.MaterialIdentifier')),
                ('material_type', models.ManyToManyField(related_name='material_material_type', to='core.MaterialType')),
                ('property', models.ManyToManyField(related_name='material_property', to='core.Property')),
                ('status', models.ForeignKey(blank=True, db_column='status_uuid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='material_status', to='core.Status')),
            ],
            options={
                'db_table': 'material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.PersonTable')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
