# Generated by Django 2.2.3 on 2019-08-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('document', models.BinaryField()),
                ('doctype', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notetext', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
