# Generated by Django 3.0.14 on 2021-05-22 01:17

import core.models.core_tables
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdocumentX',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='edocument_x_uuid', editable=False, primary_key=True, serialize=False)),
                ('ref_edocument_uuid', core.models.core_tables.RetUUIDField()),
            ],
            options={
                'db_table': 'edocument_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialIdentifierX',
            fields=[
                ('uuid', core.models.core_tables.RetUUIDField(db_column='material_refname_x_uuid', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'material_refname_x',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoteX',
            fields=[
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('uuid', core.models.core_tables.RetUUIDField(db_column='note_x_uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ref_note', core.models.core_tables.RetUUIDField(db_column='ref_note_uuid')),
            ],
            options={
                'db_table': 'note_x',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MaterialIndentifierX',
        ),
        migrations.DeleteModel(
            name='Note_x',
        ),
        migrations.AlterModelTable(
            name='measure',
            table='measure',
        ),
        migrations.AlterModelTable(
            name='measuredef',
            table='measure_def',
        ),
        migrations.AlterModelTable(
            name='measuretype',
            table='measure_type',
        ),
        migrations.AlterModelTable(
            name='parameterdef',
            table='parameter_def',
        ),
    ]
