# Generated by Django 3.1 on 2020-12-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpassword',
            name='organization',
            field=models.OneToOneField(db_column='parent_uuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_password_organization', to='core.organizationtable'),
        ),
    ]
