# Generated by Django 2.2.3 on 2019-08-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('data_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('website_url', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
                ('systemtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SystemType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('suffix', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('data_file', models.BinaryField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aggregate')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Measure')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='measure',
            name='measure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MeasureType'),
        ),
        migrations.AddField(
            model_name='measure',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note'),
        ),
        migrations.CreateModel(
            name='IngredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('ingredient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IngredientType')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor')),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aggregate')),
                ('descriptor', models.ManyToManyField(to='core.Descriptor')),
                ('ingredient_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IngredientRef')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Outcome')),
                ('parent_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Experiment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('num_value', models.FloatField()),
                ('blob_value', models.BinaryField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='descriptor',
            name='descriptor_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DescriptorClass'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='descriptor_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DescriptorValue'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note'),
        ),
        migrations.AddField(
            model_name='descriptor',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status'),
        ),
        migrations.AddField(
            model_name='actor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='actor',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.System'),
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('seq', models.IntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Action')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Action')),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aggregate')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ingredient')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Measure')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('add_dt', models.DateTimeField()),
                ('mod_dt', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='action',
            name='action_def',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ActionDef'),
        ),
        migrations.AddField(
            model_name='action',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Measure'),
        ),
        migrations.AddField(
            model_name='action',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Note'),
        ),
        migrations.AddField(
            model_name='action',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Actor'),
        ),
    ]
