# Generated by Django 2.2.12 on 2020-06-11 21:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('calculation_uuid', models.UUIDField(db_column='calculation_uuid', primary_key=True, serialize=False)),
                ('in_val', models.TextField(blank=True, null=True)),
                ('in_type', models.CharField(blank=True, max_length=255, null=True)),
                ('in_val_type', models.TextField(blank=True, null=True)),
                ('in_val_value', models.TextField(blank=True, null=True)),
                ('in_val_unit', models.TextField(blank=True, null=True)),
                ('in_opt_val', models.TextField(blank=True, null=True)),
                ('in_opt_val_type', models.TextField(blank=True, null=True)),
                ('in_opt_val_value', models.TextField(blank=True, null=True)),
                ('in_opt_val_unit', models.TextField(blank=True, null=True)),
                ('out_val', models.TextField(blank=True, null=True)),
                ('out_val_type', models.TextField(blank=True, null=True)),
                ('out_val_value', models.TextField(blank=True, null=True)),
                ('out_val_unit', models.TextField(blank=True, null=True)),
                ('calculation_alias_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('notetext', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calc_definition', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
                ('out_type', models.CharField(blank=True, max_length=255, null=True)),
                ('systemtool_name', models.CharField(blank=True, max_length=1023, null=True)),
                ('systemtool_type_description', models.CharField(blank=True, max_length=1023, null=True)),
                ('systemtool_vendor_organization', models.CharField(blank=True, db_column='systemtool_vendor_organization', max_length=1023, null=True)),
                ('systemtool_version', models.CharField(blank=True, max_length=1023, null=True)),
                ('actor_description', models.CharField(blank=True, max_length=1023, null=True)),
            ],
            options={
                'db_table': 'vw_calculation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationDef',
            fields=[
                ('calculation_def_uuid', models.UUIDField(db_column='calculation_def_uuid', primary_key=True, serialize=False)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('calc_definition', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1023, null=True)),
                ('in_type', models.CharField(blank=True, max_length=255, null=True)),
                ('out_type', models.CharField(blank=True, max_length=255, null=True)),
                ('systemtool_name', models.CharField(blank=True, max_length=255, null=True)),
                ('systemtool_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('systemtool_vendor_organization', models.CharField(blank=True, db_column='systemtool_vendor_organization', max_length=255, null=True)),
                ('systemtool_version', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_calculation_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperimentMeasureCalculation',
            fields=[
                ('uid', models.CharField(db_column='uid', max_length=255, primary_key=True, serialize=False)),
                ('row_to_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'vw_experiment_measure_calculation_json',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryMaterial',
            fields=[
                ('inventory_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('inventory_description', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_part_no', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_onhand_amt', models.FloatField(blank=True, null=True)),
                ('inventory_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_create_date', models.DateTimeField(blank=True, null=True)),
                ('inventory_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('inventory_location', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_status', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_description', models.CharField(blank=True, max_length=255, null=True)),
                ('org_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_status', models.CharField(blank=True, max_length=255, null=True)),
                ('material_create_date', models.DateTimeField()),
                ('material_name', models.CharField(blank=True, max_length=255, null=True)),
                ('material_abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('material_inchi', models.CharField(blank=True, max_length=255, null=True)),
                ('material_inchikey', models.CharField(blank=True, max_length=255, null=True)),
                ('material_molecular_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('material_smiles', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_inventory_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LatestSystemtool',
            fields=[
                ('systemtool_uuid', models.UUIDField(db_column='systemtool_uuid', primary_key=True, serialize=False)),
                ('systemtool_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('systemtool_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('ver', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_description', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_latest_systemtool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialCalculationJson',
            fields=[
                ('material_uuid', models.UUIDField(db_column='material_uuid', primary_key=True, serialize=False)),
                ('material_status', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField()),
                ('abbreviation', models.CharField(blank=True, db_column='abbreviation', max_length=255, null=True)),
                ('chemical_name', models.CharField(blank=True, db_column='chemical_name', max_length=255, null=True)),
                ('inchi', models.CharField(blank=True, db_column='inchi', max_length=255, null=True)),
                ('inchikey', models.CharField(blank=True, db_column='inchikey', max_length=255, null=True)),
                ('molecular_formula', models.CharField(blank=True, db_column='molecular_formula', max_length=255, null=True)),
                ('smiles', models.CharField(blank=True, db_column='smiles', max_length=255, null=True)),
                ('calculation_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'vw_material_calculation_json',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialRefnameType',
            fields=[
                ('material_refname_type_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notetext', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_material_refname_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('material_type_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('notetext', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_material_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('tag_short_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_description', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('tag_type_short_descr', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_description', models.CharField(blank=True, max_length=255, null=True)),
                ('notetext', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vw_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('tag_type_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_description', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_tag_type',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ViewActor',
        ),
        migrations.DeleteModel(
            name='ViewInventory',
        ),
        migrations.DeleteModel(
            name='ViewInventoryMaterial',
        ),
        migrations.DeleteModel(
            name='ViewLatestSystemtool',
        ),
        migrations.DeleteModel(
            name='ViewMaterial',
        ),
        migrations.DeleteModel(
            name='ViewMaterialDescriptor',
        ),
        migrations.DeleteModel(
            name='ViewMaterialRefnameType',
        ),
        migrations.DeleteModel(
            name='ViewMaterialType',
        ),
        migrations.DeleteModel(
            name='ViewMDescriptor',
        ),
        migrations.DeleteModel(
            name='ViewMDescriptorDef',
        ),
        migrations.DeleteModel(
            name='ViewNote',
        ),
        migrations.DeleteModel(
            name='ViewOrganization',
        ),
        migrations.DeleteModel(
            name='ViewPerson',
        ),
        migrations.DeleteModel(
            name='ViewStatus',
        ),
        migrations.DeleteModel(
            name='ViewTag',
        ),
        migrations.DeleteModel(
            name='ViewTagType',
        ),
        migrations.AlterModelTable(
            name='actor',
            table='vw_actor',
        ),
        migrations.AlterModelTable(
            name='edocument',
            table='vw_edocument',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='vw_inventory',
        ),
        migrations.AlterModelTable(
            name='material',
            table='vw_material',
        ),
        migrations.AlterModelTable(
            name='note',
            table='vw_note',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='vw_organization',
        ),
        migrations.AlterModelTable(
            name='person',
            table='vw_person',
        ),
        migrations.AlterModelTable(
            name='status',
            table='vw_status',
        ),
    ]
