# Generated by Django 3.0.2 on 2020-01-06 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadhcinventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 33, 51, 625357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loadhcinventory',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 33, 51, 625334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loadlblinventory',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 33, 51, 625658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='loadlblinventory',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 6, 17, 33, 51, 625642, tzinfo=utc)),
        ),
    ]
