# Generated by Django 3.0.2 on 2020-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200106_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadhcinventory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loadhcinventory',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loadlblinventory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loadlblinventory',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
