# Generated by Django 2.2.13 on 2020-06-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200611_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdfDef',
            fields=[
                ('udf_def_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('valtype', models.CharField(blank=True, max_length=255, null=True)),
                ('notetext', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'vw_udf_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSystemtoolType',
            fields=[
                ('systemtool_type_uuid', models.UUIDField(db_column='systemtool_type_uuid', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notetext', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_systemtool_type',
                'managed': False,
            },
        ),
    ]
