# Generated by Django 2.2.14 on 2020-07-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200717_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRefnameDef',
            fields=[
                ('material_refname_def_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_material_refname_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note_x',
            fields=[
                ('note_x_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('add_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('ref_note_uuid', models.UUIDField()),
            ],
            options={
                'db_table': 'note_x',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MaterialRefnameType',
        ),
        migrations.DeleteModel(
            name='ViewSystemtoolType',
        ),
        migrations.AlterModelTable(
            name='systemtooltype',
            table='vw_systemtool_type',
        ),
    ]
