# Generated by Django 3.0.8 on 2020-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200720_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_X',
            fields=[
                ('tag_x_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('ref_tag_uuid', models.UUIDField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_tag_x',
                'managed': False,
            },
        ),
    ]
