# Generated by Django 3.1 on 2020-09-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProperty',
            fields=[
                ('property_x_uuid', models.UUIDField(db_column='property_x_uuid', primary_key=True, serialize=False)),
                ('property_description', models.CharField(blank=True, db_column='property_description', editable=False, max_length=255, null=True)),
                ('property_short_description', models.CharField(blank=True, db_column='property_short_description', editable=False, max_length=255, null=True)),
                ('value', models.CharField(blank=True, db_column='val_val', max_length=255, null=True)),
                ('actor_description', models.CharField(blank=True, db_column='actor_description', editable=False, max_length=255, null=True)),
                ('status_description', models.CharField(blank=True, db_column='status_description', editable=False, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_material_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyDef',
            fields=[
                ('uuid', models.UUIDField(db_column='property_def_uuid', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, db_column='short_description', max_length=255, null=True)),
                ('val_unit', models.CharField(blank=True, db_column='valunit', max_length=255, null=True)),
                ('actor_description', models.CharField(blank=True, db_column='actor_description', editable=False, max_length=255, null=True)),
                ('status_description', models.CharField(blank=True, db_column='status_description', editable=False, max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_property_def',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDef',
            fields=[
                ('uuid', models.UUIDField(db_column='type_def_uuid', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='category', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vw_type_def',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
