##

GET http://escalate.sd2e.org/api/experimentmeasurecalculation/2018-12-04T01_52_47.768958%2B00_00_LBL_A1

###

GET http://escalate.sd2e.org/api/experimentmeasurecalculation/


###

GET http://escalate.sd2e.org/api/systemtool/?systemtool_name=standardize

###
GET http://localhost:8000/api/experimentmeasurecalculation/2018-12-04T01_52_47.768958%2B00_00_LBL_A1

###

GET http://localhost:8000/api/experimentmeasurecalculation/?fields=uid


###

GET http://localhost:8000/api/systemtool/?systemtool_name=standardize

###

POST http://localhost:8000/api/login
content-type: application/json

{
  "username": "vshekar",
  "password": "copperhead123"
  
}

###
POST http://localhost:8000/api/person/
content-type: application/json

{
 "first_name": "S",
 "last_name": "V" 
  
}

###
POST http://localhost:8000/api/person/
Authorization: Token b1d7184e1257df774d6f20321ef767e0648a9e8c
content-type: application/json

{
 "first_name": "S",
 "last_name": "V" 
  
}