"""
Code used to generate this data
import pprint
from rest_api.utils import rest_serializer_views
from core.models.view_tables import *
from core.models.core_tables import *
result = {}
for model_name in rest_serializer_views:
    all_fields = [field.name for field in globals()[model_name]._meta._get_fields(reverse=False)] + ['url']
    result[model_name] = all_fields

pretty_result = pprint.pformat(result)
with open('./rest_api/serializer_fields.py', 'a') as f:
    f.write(pretty_result)

"""
{'ActionParameter': ['uuid',
                     'action',
                     'parameter_def',
                     'parameter_val',
                     'actor',
                     'status',
                     'add_date',
                     'mod_date',
                     'url'],
 'Actor': ['uuid',
           'organization',
           'person',
           'systemtool',
           'description',
           'status',
           'add_date',
           'mod_date',
           'url'],
 'BillOfMaterials': ['uuid',
                     'description',
                     'experiment',
                     'actor',
                     'status',
                     'add_date',
                     'mod_date',
                     'url'],
 'BomCompositeMaterial': ['uuid',
                          'description',
                          'bom_material',
                          'composite_material',
                          'component',
                          'actor',
                          'status',
                          'add_date',
                          'mod_date',
                          'url'],
 'BomMaterial': ['uuid',
                 'description',
                 'bom',
                 'inventory_material',
                 'material',
                 'alloc_amt_val',
                 'used_amt_val',
                 'putback_amt_val',
                 'actor',
                 'status',
                 'add_date',
                 'mod_date',
                 'url'],
 'Calculation': ['uuid',
                 'in_val',
                 'in_opt_val',
                 'out_val',
                 'calculation_alias_name',
                 'status',
                 'calculation_def',
                 'short_name',
                 'calc_definition',
                 'description',
                 'systemtool',
                 'actor',
                 'add_date',
                 'mod_date',
                 'url'],
 'CalculationDef': ['uuid',
                    'short_name',
                    'calc_definition',
                    'description',
                    'in_source',
                    'in_type',
                    'in_opt_source',
                    'in_opt_type',
                    'out_type',
                    'systemtool',
                    'actor',
                    'add_date',
                    'mod_date',
                    'parameter_def',
                    'url'],
 'CompositeMaterial': ['uuid',
                       'composite',
                       'composite_description',
                       'composite_flg',
                       'component',
                       'component_description',
                       'addressable',
                       'actor',
                       'status',
                       'add_date',
                       'mod_date',
                       'property',
                       'url'],
 'Condition': ['uuid',
               'condition_calculation',
               'condition_description',
               'condition_def',
               'calculation_description',
               'in_val',
               'out_val',
               'actor',
               'actor_description',
               'status',
               'status_description',
               'add_date',
               'mod_date',
               'url'],
 'ConditionCalculationDefAssign': ['uuid',
                                   'condition_def',
                                   'calculation_def',
                                   'add_date',
                                   'mod_date',
                                   'url'],
 'ConditionDef': ['uuid',
                  'description',
                  'actor',
                  'actor_description',
                  'status',
                  'add_date',
                  'mod_date',
                  'calculation_def',
                  'url'],
 'Experiment': ['uuid',
                'ref_uid',
                'description',
                'parent',
                'owner',
                'owner_description',
                'operator',
                'operator_description',
                'lab',
                'lab_description',
                'status',
                'status_description',
                'add_date',
                'mod_date',
                'workflow',
                'url'],
 'ExperimentWorkflow': ['uuid',
                        'experiment',
                        'experiment_ref_uid',
                        'experiment_description',
                        'experiment_workflow_seq',
                        'workflow',
                        'workflow_type_uuid',
                        'url'],
 'Inventory': ['uuid',
               'description',
               'owner',
               'owner_description',
               'operator',
               'operator_description',
               'lab',
               'lab_description',
               'status',
               'status_description',
               'actor',
               'actor_description',
               'add_date',
               'mod_date',
               'url'],
 'InventoryMaterial': ['uuid',
                       'description',
                       'inventory',
                       'inventory_description',
                       'material',
                       'material_description',
                       'material_consumable',
                       'material_composite_flg',
                       'part_no',
                       'onhand_amt',
                       'expiration_date',
                       'location',
                       'actor',
                       'actor_description',
                       'status',
                       'status_description',
                       'add_date',
                       'mod_date',
                       'url'],
 'Material': ['uuid',
              'description',
              'consumable',
              'composite_flg',
              'actor',
              'actor_description',
              'status',
              'status_description',
              'add_date',
              'mod_date',
              'property',
              'url'],
 'MaterialProperty': ['uuid',
                      'material',
                      'description',
                      'property',
                      'property_def',
                      'property_description',
                      'property_short_description',
                      'value',
                      'actor',
                      'actor_description',
                      'status',
                      'status_description',
                      'add_date',
                      'mod_date',
                      'url'],
 'MaterialRefnameDef': ['uuid', 'description', 'add_date', 'mod_date', 'url'],
 'MaterialType': ['uuid', 'description', 'add_date', 'mod_date', 'url'],
 'Measure': ['uuid',
             'measure_type',
             'ref_measure',
             'description',
             'measure_value',
             'actor_uuid',
             'actor_description',
             'status_uuid',
             'status_description',
             'add_date',
             'mod_date',
             'url'],
 'MeasureType': ['uuid',
                 'description',
                 'actor_uuid',
                 'actor_description',
                 'status_uuid',
                 'status_description',
                 'add_date',
                 'mod_date',
                 'url'],
 'Note_x': ['uuid', 'ref_note', 'note', 'add_date', 'mod_date', 'url'],
 'Organization': ['uuid',
                  'description',
                  'full_name',
                  'short_name',
                  'address1',
                  'address2',
                  'city',
                  'state_province',
                  'zip',
                  'country',
                  'website_url',
                  'phone',
                  'parent',
                  'parent_org_full_name',
                  'add_date',
                  'mod_date',
                  'url'],
 'Outcome': ['uuid',
             'description',
             'experiment',
             'actor',
             'actor_description',
             'status',
             'status_description',
             'add_date',
             'mod_date',
             'url'],
 'Parameter': ['uuid',
               'parameter_def',
               'parameter_def_description',
               'parameter_val',
               'actor',
               'actor_description',
               'status',
               'status_description',
               'add_date',
               'mod_date',
               'url'],
 'ParameterDef': ['uuid',
                  'description',
                  'val_type',
                  'default_val',
                  'required',
                  'actor',
                  'actor_description',
                  'status',
                  'status_description',
                  'add_date',
                  'mod_date',
                  'url'],
 'Person': ['uuid',
            'first_name',
            'last_name',
            'middle_name',
            'address1',
            'address2',
            'city',
            'state_province',
            'zip',
            'country',
            'phone',
            'email',
            'title',
            'suffix',
            'add_date',
            'mod_date',
            'organization',
            'organization_full_name',
            'added_organization',
            'url'],
 'Property': ['uuid',
              'property_def',
              'short_description',
              'property_val',
              'actor',
              'actor_description',
              'status',
              'status_description',
              'add_date',
              'mod_date',
              'url'],
 'PropertyDef': ['uuid',
                 'description',
                 'short_description',
                 'val_type',
                 'val_unit',
                 'actor',
                 'actor_description',
                 'status',
                 'status_description',
                 'add_date',
                 'mod_date',
                 'url'],
 'Status': ['uuid', 'description', 'add_date', 'mod_date', 'url'],
 'Systemtool': ['uuid',
                'systemtool_name',
                'description',
                'vendor_organization',
                'organization_fullname',
                'systemtool_type',
                'systemtool_type_description',
                'model',
                'serial',
                'ver',
                'add_date',
                'mod_date',
                'url'],
 'SystemtoolType': ['uuid', 'description', 'add_date', 'mod_date', 'url'],
 'Tag': ['uuid',
         'display_text',
         'description',
         'actor',
         'actor_description',
         'add_date',
         'mod_date',
         'tag_type',
         'type',
         'type_description',
         'url'],
 'TagType': ['uuid', 'type', 'description', 'add_date', 'mod_date', 'url'],
 'TypeDef': ['uuid', 'category', 'description', 'add_date', 'mod_date', 'url'],
 'UdfDef': ['uuid',
            'description',
            'val_type',
            'val_type_description',
            'unit',
            'add_date',
            'mod_date',
            'url'],
 'WorkflowObject': ['uuid',
                    'workflow',
                    'action',
                    'condition',
                    'object_uuid',
                    'object_type',
                    'object_description',
                    'object_def_description',
                    'add_date',
                    'mod_date',
                    'url'],
 'WorkflowStep': ['uuid',
                  'workflow',
                  'workflow_description',
                  'parent',
                  'parent_object_type',
                  'parent_object_description',
                  'parent_path',
                  'conditional_val',
                  'conditional_value',
                  'status',
                  'status_description',
                  'add_date',
                  'mod_date',
                  'workflow_object',
                  'url'],
 'WorkflowType': ['uuid', 'description', 'add_date', 'mod_date', 'url']}