/*
 Navicat Premium Data Transfer

 Source Server         : postgres12 escalate
 Source Server Type    : PostgreSQL
 Source Server Version : 120003
 Source Host           : localhost:5432
 Source Catalog        : escalate
 Source Schema         : dev

 Target Server Type    : PostgreSQL
 Target Server Version : 120003
 File Encoding         : 65001

 Date: 08/06/2020 13:06:50
*/


-- ----------------------------
-- Table structure for load_v2_iodides
-- ----------------------------
DROP TABLE IF EXISTS "load_v2_iodides";
CREATE TABLE "load_v2_iodides" (
  "_exp_no" varchar(255) COLLATE "pg_catalog"."default",
  "_out_crystalscore" int8,
  "_rxn_actual_bulk_temperature_c" float8,
  "_rxn_mixingtime_s" float8,
  "_rxn_mixingtime1_s" float8,
  "_rxn_mixingtime2_s" float8,
  "_rxn_preheattemperature_c" float8,
  "_rxn_reactiontime_s" float8,
  "_rxn_stirrate_rpm" float8,
  "_rxn_temperaturecool_c" float8,
  "_rxn_temperature_c" float8,
  "_rxn_molarity_acid" float8,
  "_rxn_molarity_inorganic" float8,
  "_rxn_molarity_organic" float8,
  "_rxn_molarity_solvent" float8,
  "_calc_ratio_acid_molarity_inorganic_molarity" float8,
  "_calc_ratio_acid_molarity_organic_molarity" float8,
  "_calc_ratio_acid_molarity_solvent_molarity" float8,
  "_calc_ratio_inorganic_molarity_acid_molarity" float8,
  "_calc_ratio_inorganic_molarity_organic_molarity" float8,
  "_calc_ratio_inorganic_molarity_solvent_molarity" float8,
  "_calc_ratio_organic_molarity_acid_molarity" float8,
  "_calc_ratio_organic_molarity_inorganic_molarity" float8,
  "_calc_ratio_organic_molarity_solvent_molarity" float8,
  "_calc_ratio_solvent_molarity_acid_molarity" float8,
  "_calc_ratio_solvent_molarity_inorganic_molarity" float8,
  "_calc_ratio_solvent_molarity_organic_molarity" float8,
  "_calc_ratiobytype_acid_0_molarity_inorganic_0_molarity" float8,
  "_calc_ratiobytype_acid_0_molarity_inorganic_1_molarity" float8,
  "_calc_ratiobytype_acid_0_molarity_organic_0_molarity" float8,
  "_calc_ratiobytype_acid_0_molarity_organic_1_molarity" float8,
  "_calc_ratiobytype_acid_0_molarity_solvent_0_molarity" float8,
  "_calc_ratiobytype_acid_0_molarity_solvent_1_molarity" float8,
  "_calc_ratiobytype_inorganic_0_molarity_acid_0_molarity" float8,
  "_calc_ratiobytype_inorganic_0_molarity_inorganic_1_molarity" float8,
  "_calc_ratiobytype_inorganic_0_molarity_organic_0_molarity" float8,
  "_calc_ratiobytype_inorganic_0_molarity_organic_1_molarity" float8,
  "_calc_ratiobytype_inorganic_0_molarity_solvent_0_molarity" float8,
  "_calc_ratiobytype_inorganic_0_molarity_solvent_1_molarity" float8,
  "_calc_ratiobytype_inorganic_1_molarity_acid_0_molarity" float8,
  "_calc_ratiobytype_inorganic_1_molarity_inorganic_0_molarity" float8,
  "_calc_ratiobytype_inorganic_1_molarity_organic_0_molarity" float8,
  "_calc_ratiobytype_inorganic_1_molarity_organic_1_molarity" float8,
  "_calc_ratiobytype_inorganic_1_molarity_solvent_0_molarity" float8,
  "_calc_ratiobytype_inorganic_1_molarity_solvent_1_molarity" float8,
  "_calc_ratiobytype_organic_0_molarity_acid_0_molarity" float8,
  "_calc_ratiobytype_organic_0_molarity_organic_1_molarity" float8,  
  "_calc_ratiobytype_organic_0_molarity_inorganic_0_molarity" float8,
  "_calc_ratiobytype_organic_0_molarity_inorganic_1_molarity" float8,
  "_calc_ratiobytype_organic_0_molarity_solvent_0_molarity" float8,
  "_calc_ratiobytype_organic_0_molarity_solvent_1_molarity" float8,
  "_calc_ratiobytype_organic_1_molarity_acid_0_molarity" float8,
  "_calc_ratiobytype_organic_1_molarity_organic_0_molarity" float8,  
  "_calc_ratiobytype_organic_1_molarity_inorganic_0_molarity" float8,
  "_calc_ratiobytype_organic_1_molarity_inorganic_1_molarity" float8,
  "_calc_ratiobytype_organic_1_molarity_solvent_0_molarity" float8,
  "_calc_ratiobytype_organic_1_molarity_solvent_1_molarity" float8,
  "_calc_ratiobytype_solvent_0_molarity_acid_0_molarity" float8,
  "_calc_ratiobytype_solvent_0_molarity_inorganic_0_molarity" float8,
  "_calc_ratiobytype_solvent_0_molarity_inorganic_1_molarity" float8,
  "_calc_ratiobytype_solvent_0_molarity_organic_0_molarity" float8,
  "_calc_ratiobytype_solvent_0_molarity_organic_1_molarity" float8,
  "_calc_ratiobytype_solvent_0_molarity_solvent_1_molarity" float8,
  "_calc_ratiobytype_solvent_1_molarity_acid_0_molarity" float8,
  "_calc_ratiobytype_solvent_1_molarity_inorganic_0_molarity" float8,
  "_calc_ratiobytype_solvent_1_molarity_inorganic_1_molarity" float8,
  "_calc_ratiobytype_solvent_1_molarity_organic_0_molarity" float8,
  "_calc_ratiobytype_solvent_1_molarity_organic_1_molarity" float8,
  "_calc_ratiobytype_solvent_1_molarity_solvent_0_molarity" float8,
  "_calc_weightedhansen_deltad" float8,
  "_calc_weightedhansen_deltah" float8,
  "_calc_weightedhansen_deltap" float8,
  "_calc_acid_solvent_average_hansen_deltad" float8,
  "_calc_acid_solvent_average_hansen_deltah" float8,
  "_calc_acid_solvent_average_hansen_deltap" float8,
  "_feat_acid_0_hansentriple_volume_amount" float8,
  "_feat_acid_0_hansentriple_deltad_amount" float8,
  "_feat_acid_0_hansentriple_deltah_amount" float8,
  "_feat_acid_0_hansentriple_deltap_amount" float8,
  "_feat_acid_0_hansentriple_deltat_amount" float8,
  "_feat_acid_0_index" int8,  
  "_feat_inorganic_0_fr_halogen" int8,
  "_feat_inorganic_1_fr_halogen" int8,  
  "_feat_organic_0_fr_amidine" int8,
  "_feat_organic_0_fr_dihydropyridine" int8,
  "_feat_organic_0_fr_guanido" int8,
  "_feat_organic_0_fr_halogen" int8,
  "_feat_organic_0_fr_piperdine" int8,
  "_feat_organic_0_fr_piperzine" int8,
  "_feat_organic_0_fr_pyridine" int8,
  "_feat_organic_1_fr_amidine" int8,
  "_feat_organic_1_fr_dihydropyridine" int8,
  "_feat_organic_1_fr_guanido" int8,
  "_feat_organic_1_fr_halogen" int8,
  "_feat_organic_1_fr_piperdine" int8,
  "_feat_organic_1_fr_piperzine" int8,
  "_feat_organic_1_fr_pyridine" int8,
  "_feat_solvent_0_hansentriple_volume_amount" float8,
  "_feat_solvent_0_hansentriple_deltad_amount" float8,
  "_feat_solvent_0_hansentriple_deltah_amount" float8,
  "_feat_solvent_0_hansentriple_deltap_amount" float8,
  "_feat_solvent_0_hansentriple_deltat_amount" float8,
  "_feat_solvent_0_index" int8, 
  "_feat_solvent_1_hansentriple_volume_amount" float8,
  "_feat_solvent_1_hansentriple_deltad_amount" float8,
  "_feat_solvent_1_hansentriple_deltah_amount" float8,
  "_feat_solvent_1_hansentriple_deltap_amount" float8,
  "_feat_solvent_1_hansentriple_deltat_amount" float8,
  "_feat_solvent_1_index" int8,   
  "_feat_halide_electronegativity" float8,  
  "_raw_user_generated_experimentname" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_batch_count" int8,
  "_raw_model_predicted" float8,
  "_raw_challengeproblem" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_expver" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_genver" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_datecreated" date,
  "_raw_jobserial" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_lab" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_labwareid" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_notebook" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_protocol" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_actual_amount" float8,
  "_raw_reagent_0_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_nominal_amount" float8,
  "_raw_reagent_0_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_0_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_1_actual_amount" float8,
  "_raw_reagent_0_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_1_nominal_amount" float8,
  "_raw_reagent_0_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_2_actual_amount" float8,
  "_raw_reagent_0_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_2_nominal_amount" float8,
  "_raw_reagent_0_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_3_actual_amount" float8,
  "_raw_reagent_0_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_chemicals_3_nominal_amount" float8,
  "_raw_reagent_0_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_date" date,
  "_raw_reagent_0_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_0_duration" float8,
  "_raw_reagent_0_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_0_stir" float8,
  "_raw_reagent_0_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_0_temperature" float8,
  "_raw_reagent_0_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_1_temperature" float8,
  "_raw_reagent_0_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_instructions_2_volume" float8,
  "_raw_reagent_0_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_0_volume" float8,
  "_raw_reagent_1_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_0_actual_amount" float8,
  "_raw_reagent_1_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_0_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_0_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_0_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_0_nominal_amount" float8,
  "_raw_reagent_1_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_0_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_0_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_actual_amount" float8,
  "_raw_reagent_1_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_nominal_amount" float8,
  "_raw_reagent_1_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_1_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_actual_amount" float8,
  "_raw_reagent_1_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_nominal_amount" float8,
  "_raw_reagent_1_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_2_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_3_actual_amount" float8,
  "_raw_reagent_1_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_chemicals_3_nominal_amount" float8,
  "_raw_reagent_1_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_date" date,
  "_raw_reagent_1_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_0_duration" float8,
  "_raw_reagent_1_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_0_stir" float8,
  "_raw_reagent_1_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_0_temperature" float8,
  "_raw_reagent_1_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_1_temperature" float8,
  "_raw_reagent_1_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_instructions_2_volume" float8,
  "_raw_reagent_1_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_1_volume" float8,
  "_raw_reagent_2_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_0_actual_amount" float8,
  "_raw_reagent_2_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_0_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_0_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_0_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_0_nominal_amount" float8,
  "_raw_reagent_2_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_0_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_0_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_actual_amount" float8,
  "_raw_reagent_2_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_nominal_amount" float8,
  "_raw_reagent_2_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_1_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_2_actual_amount" float8,
  "_raw_reagent_2_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_2_nominal_amount" float8,
  "_raw_reagent_2_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_3_actual_amount" float8,
  "_raw_reagent_2_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_chemicals_3_nominal_amount" float8,
  "_raw_reagent_2_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_date" date,
  "_raw_reagent_2_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_0_duration" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_0_stir" float8,
  "_raw_reagent_2_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_0_temperature" float8,
  "_raw_reagent_2_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_1_temperature" float8,
  "_raw_reagent_2_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_instructions_2_volume" float8,
  "_raw_reagent_2_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_2_volume" float8,
  "_raw_reagent_3_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_0_actual_amount" float8,
  "_raw_reagent_3_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_0_nominal_amount" float8,
  "_raw_reagent_3_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_1_actual_amount" float8,
  "_raw_reagent_3_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_1_nominal_amount" float8,
  "_raw_reagent_3_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_2_actual_amount" float8,
  "_raw_reagent_3_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_2_nominal_amount" float8,
  "_raw_reagent_3_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_3_actual_amount" float8,
  "_raw_reagent_3_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_chemicals_3_nominal_amount" float8,
  "_raw_reagent_3_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_date" date,
  "_raw_reagent_3_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_0_duration" float8,
  "_raw_reagent_3_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_0_stir" float8,
  "_raw_reagent_3_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_0_temperature" float8,
  "_raw_reagent_3_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_1_temperature" float8,
  "_raw_reagent_3_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_instructions_2_volume" float8,
  "_raw_reagent_3_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_3_volume" float8,
  "_raw_reagent_4_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_0_actual_amount" float8,
  "_raw_reagent_4_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_0_nominal_amount" float8,
  "_raw_reagent_4_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_1_actual_amount" float8,
  "_raw_reagent_4_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_1_nominal_amount" float8,
  "_raw_reagent_4_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_2_actual_amount" float8,
  "_raw_reagent_4_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_2_nominal_amount" float8,
  "_raw_reagent_4_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_3_actual_amount" float8,
  "_raw_reagent_4_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_chemicals_3_nominal_amount" float8,
  "_raw_reagent_4_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_date" date,
  "_raw_reagent_4_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_0_duration" float8,
  "_raw_reagent_4_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_0_stir" float8,
  "_raw_reagent_4_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_0_temperature" float8,
  "_raw_reagent_4_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_1_temperature" float8,
  "_raw_reagent_4_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_instructions_2_volume" float8,
  "_raw_reagent_4_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_4_volume" float8,
  "_raw_reagent_5_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_0_actual_amount" float8,
  "_raw_reagent_5_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_0_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_0_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_0_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_0_nominal_amount" float8,
  "_raw_reagent_5_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_0_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_0_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_1_actual_amount" float8,
  "_raw_reagent_5_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_1_nominal_amount" float8,
  "_raw_reagent_5_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_2_actual_amount" float8,
  "_raw_reagent_5_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_2_nominal_amount" float8,
  "_raw_reagent_5_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_3_actual_amount" float8,
  "_raw_reagent_5_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_chemicals_3_nominal_amount" float8,
  "_raw_reagent_5_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_date" date,
  "_raw_reagent_5_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_0_duration" float8,
  "_raw_reagent_5_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_0_stir" float8,
  "_raw_reagent_5_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_0_temperature" float8,
  "_raw_reagent_5_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_1_temperature" float8,
  "_raw_reagent_5_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_instructions_2_volume" float8,
  "_raw_reagent_5_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_5_volume" float8,
  "_raw_reagent_6_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_0_actual_amount" float8,
  "_raw_reagent_6_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_0_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_0_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_0_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_0_nominal_amount" float8,
  "_raw_reagent_6_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_0_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_0_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_1_actual_amount" float8,
  "_raw_reagent_6_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_1_nominal_amount" float8,
  "_raw_reagent_6_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_2_actual_amount" float8,
  "_raw_reagent_6_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_2_nominal_amount" float8,
  "_raw_reagent_6_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_3_actual_amount" float8,
  "_raw_reagent_6_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_chemicals_3_nominal_amount" float8,
  "_raw_reagent_6_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_date" date,
  "_raw_reagent_6_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_0_duration" float8,
  "_raw_reagent_6_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_0_stir" float8,
  "_raw_reagent_6_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_0_temperature" float8,
  "_raw_reagent_6_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_1_temperature" float8,
  "_raw_reagent_6_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_instructions_2_volume" float8,
  "_raw_reagent_6_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_model" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_model_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_name" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_object" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_object_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_6_volume" float8,
  "_raw_reagent_7_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_0_actual_amount" float8,
  "_raw_reagent_7_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_0_nominal_amount" float8,
  "_raw_reagent_7_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_1_actual_amount" float8,
  "_raw_reagent_7_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_1_nominal_amount" float8,
  "_raw_reagent_7_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_2_actual_amount" float8,
  "_raw_reagent_7_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_2_nominal_amount" float8,
  "_raw_reagent_7_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_3_actual_amount" float8,
  "_raw_reagent_7_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_chemicals_3_nominal_amount" float8,
  "_raw_reagent_7_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_date" date,
  "_raw_reagent_7_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_0_duration" float8,
  "_raw_reagent_7_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_0_stir" float8,
  "_raw_reagent_7_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_0_temperature" float8,
  "_raw_reagent_7_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_1_temperature" float8,
  "_raw_reagent_7_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_instructions_2_volume" float8,
  "_raw_reagent_7_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_7_volume" float8,
  "_raw_reagent_8_chemicals_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_0_actual_amount" float8,
  "_raw_reagent_8_chemicals_0_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_0_nominal_amount" float8,
  "_raw_reagent_8_chemicals_0_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_1_actual_amount" float8,
  "_raw_reagent_8_chemicals_1_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_1_nominal_amount" float8,
  "_raw_reagent_8_chemicals_1_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_2_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_2_actual_amount" float8,
  "_raw_reagent_8_chemicals_2_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_2_nominal_amount" float8,
  "_raw_reagent_8_chemicals_2_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_3_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_3_actual_amount" float8,
  "_raw_reagent_8_chemicals_3_actual_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_chemicals_3_nominal_amount" float8,
  "_raw_reagent_8_chemicals_3_nominal_amount_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_date" date,
  "_raw_reagent_8_id" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_0_duration" float8,
  "_raw_reagent_8_instructions_0_duration_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_0_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_0_stir" float8,
  "_raw_reagent_8_instructions_0_stir_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_0_temperature" float8,
  "_raw_reagent_8_instructions_0_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_1_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_1_temperature" float8,
  "_raw_reagent_8_instructions_1_temperature_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_2_op" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_instructions_2_volume" float8,
  "_raw_reagent_8_instructions_2_volume_units" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_operator" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_reagent_8_volume" float8,
  "_raw_timecompleted_utc" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_timecreated_utc" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_vialsite" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_modelpredictedprobability" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_identifier" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_modelname" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_notes" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_participantname" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_mmol_bamdifiroxteem-uhfffaoysa-n" float8,
  "_raw_mmol_bdagihxwwsansr-uhfffaoysa-n" float8,
  "_raw_mmol_bjdycchrzifcgn-uhfffaoysa-n" float8,
  "_raw_mmol_bvjoxyjfoynqrb-uhfffaoysa-n" float8,
  "_raw_mmol_calqkrvftwdydg-uhfffaoysa-n" float8,
  "_raw_mmol_cqwgdvvckbjlnx-uhfffaoysa-n" float8,
  "_raw_mmol_dmfmzffiqrmjqz-uhfffaoysa-n" float8,
  "_raw_mmol_fcthqyidlrrrox-uhfffaoysa-n" float8,
  "_raw_mmol_fjfijidzqadkee-uhfffaoysa-n" float8,
  "_raw_mmol_ggygjcfiyjvwip-uhfffaoysa-n" float8,
  "_raw_mmol_giapqozcviehny-uhfffaoysa-n" float8,
  "_raw_mmol_hbpsmmxresdusg-uhfffaoysa-n" float8,
  "_raw_mmol_hbzsvmfymaogrs-uhfffaoysa-n" float8,
  "_raw_mmol_iazdpxiomuyvgz-uhfffaoysa-n" float8,
  "_raw_mmol_iwnwlpunkayuaw-uhfffaoysa-n" float8,
  "_raw_mmol_jboiazwjiacnjf-uhfffaoysa-n" float8,
  "_raw_mmol_jerspyrkvmaejy-uhfffaoysa-n" float8,
  "_raw_mmol_jmxlwmifdjcgbv-uhfffaoysa-n" float8,
  "_raw_mmol_kfqarybeakaxic-uhfffaoysa-n" float8,
  "_raw_mmol_kfxbdbpogbbvmc-uhfffaoysa-n" float8,
  "_raw_mmol_koagkpnevyezdu-uhfffaoysa-n" float8,
  "_raw_mmol_lctuiscigmwmat-uhfffaoysa-n" float8,
  "_raw_mmol_llwrxqxpjmphlr-uhfffaoysa-n" float8,
  "_raw_mmol_lyhpzbkxshvbdw-uhfffaoysa-n" float8,
  "_raw_mmol_nljdbtzlvtwxrg-uhfffaoysa-n" float8,
  "_raw_mmol_nohlsfnwsbzsbw-uhfffaoysa-n" float8,
  "_raw_mmol_nxruevjqmbgvat-uhfffaoysa-n" float8,
  "_raw_mmol_pbgzccfvbveias-uhfffaoysa-n" float8,
  "_raw_mmol_ppchymcmruglhr-uhfffaoysa-n" float8,
  "_raw_mmol_pxwskgxehzhfja-uhfffaoysa-n" float8,
  "_raw_mmol_qhjpganwslemti-uhfffaoysa-n" float8,
  "_raw_mmol_qnnyedwtozodas-uhfffaoysa-n" float8,
  "_raw_mmol_qrfxelvdjsdwhx-uhfffaoysa-n" float8,
  "_raw_mmol_qzcgfuvvxnfsle-uhfffaoysa-n" float8,
  "_raw_mmol_rqqrahkhdfpbmc-uhfffaoysa-l" float8,
  "_raw_mmol_ryysznvpblklrs-uhfffaoysa-n" float8,
  "_raw_mmol_sqxjhwoxnltooo-uhfffaoysa-n" float8,
  "_raw_mmol_uphcensimpjeis-uhfffaoysa-n" float8,
  "_raw_mmol_uudrlgyroxtisk-uhfffaoysa-n" float8,
  "_raw_mmol_uvlzlkcgkylkor-uhfffaoysa-n" float8,
  "_raw_mmol_uxyjhtkqefcxbj-uhfffaoysa-n" float8,
  "_raw_mmol_uzhwwthdrvlcju-uhfffaoysa-n" float8,
  "_raw_mmol_vawhfunjdmqusb-uhfffaoysa-n" float8,
  "_raw_mmol_vmlaegaahiiwjx-uhfffaoysa-n" float8,
  "_raw_mmol_vnaauntyionohr-uhfffaoysa-n" float8,
  "_raw_mmol_wgyrinythsorgh-uhfffaoysa-n" float8,
  "_raw_mmol_xfyiczoiwsbqsk-uhfffaoysa-n" float8,
  "_raw_mmol_xqprbtxuxxvtkb-uhfffaoysa-m" float8,
  "_raw_mmol_xzucbfluebdnsj-uhfffaoysa-n" float8,
  "_raw_mmol_yejrwhavmiajkc-uhfffaoysa-n" float8,
  "_raw_mmol_ymwujeatgchhmb-uhfffaoysa-n" float8,
  "_raw_mmol_yymlriwbiszomt-uhfffaoysa-n" float8,
  "_raw_mmol_zevrffcpaltvdn-uhfffaoysa-n" float8,
  "_raw_mmol_zmxddkwlczadiw-uhfffaoysa-n" float8,
  "_raw_mmol_iswnamnoyhctsb-uhfffaoysa-n" float8,
  "_raw_mmol_pnzdzrmobiiqtc-uhfffaoysa-n" float8,
  "_raw_mmol_qwangzftsgzrpz-uhfffaoysa-n" float8,
  "_raw_mmol_zaswjuomegbqcq-uhfffaoysa-l" float8,
  "_raw_molarity_bamdifiroxteem-uhfffaoysa-n" float8,
  "_raw_molarity_bdagihxwwsansr-uhfffaoysa-n" float8,
  "_raw_molarity_bjdycchrzifcgn-uhfffaoysa-n" float8,
  "_raw_molarity_bvjoxyjfoynqrb-uhfffaoysa-n" float8,
  "_raw_molarity_calqkrvftwdydg-uhfffaoysa-n" float8,
  "_raw_molarity_cqwgdvvckbjlnx-uhfffaoysa-n" float8,
  "_raw_molarity_dmfmzffiqrmjqz-uhfffaoysa-n" float8,
  "_raw_molarity_fcthqyidlrrrox-uhfffaoysa-n" float8,
  "_raw_molarity_fjfijidzqadkee-uhfffaoysa-n" float8,
  "_raw_molarity_ggygjcfiyjvwip-uhfffaoysa-n" float8,
  "_raw_molarity_giapqozcviehny-uhfffaoysa-n" float8,
  "_raw_molarity_hbpsmmxresdusg-uhfffaoysa-n" float8,
  "_raw_molarity_hbzsvmfymaogrs-uhfffaoysa-n" float8,
  "_raw_molarity_iazdpxiomuyvgz-uhfffaoysa-n" float8,
  "_raw_molarity_iwnwlpunkayuaw-uhfffaoysa-n" float8,
  "_raw_molarity_jboiazwjiacnjf-uhfffaoysa-n" float8,
  "_raw_molarity_jerspyrkvmaejy-uhfffaoysa-n" float8,
  "_raw_molarity_jmxlwmifdjcgbv-uhfffaoysa-n" float8,
  "_raw_molarity_kfqarybeakaxic-uhfffaoysa-n" float8,
  "_raw_molarity_kfxbdbpogbbvmc-uhfffaoysa-n" float8,
  "_raw_molarity_koagkpnevyezdu-uhfffaoysa-n" float8,
  "_raw_molarity_lctuiscigmwmat-uhfffaoysa-n" float8,
  "_raw_molarity_llwrxqxpjmphlr-uhfffaoysa-n" float8,
  "_raw_molarity_lyhpzbkxshvbdw-uhfffaoysa-n" float8,
  "_raw_molarity_nljdbtzlvtwxrg-uhfffaoysa-n" float8,
  "_raw_molarity_nohlsfnwsbzsbw-uhfffaoysa-n" float8,
  "_raw_molarity_nxruevjqmbgvat-uhfffaoysa-n" float8,
  "_raw_molarity_pbgzccfvbveias-uhfffaoysa-n" float8,
  "_raw_molarity_ppchymcmruglhr-uhfffaoysa-n" float8,
  "_raw_molarity_pxwskgxehzhfja-uhfffaoysa-n" float8,
  "_raw_molarity_qhjpganwslemti-uhfffaoysa-n" float8,
  "_raw_molarity_qnnyedwtozodas-uhfffaoysa-n" float8,
  "_raw_molarity_qrfxelvdjsdwhx-uhfffaoysa-n" float8,
  "_raw_molarity_qzcgfuvvxnfsle-uhfffaoysa-n" float8,
  "_raw_molarity_rqqrahkhdfpbmc-uhfffaoysa-l" float8,
  "_raw_molarity_ryysznvpblklrs-uhfffaoysa-n" float8,
  "_raw_molarity_sqxjhwoxnltooo-uhfffaoysa-n" float8,
  "_raw_molarity_uphcensimpjeis-uhfffaoysa-n" float8,
  "_raw_molarity_uudrlgyroxtisk-uhfffaoysa-n" float8,
  "_raw_molarity_uvlzlkcgkylkor-uhfffaoysa-n" float8,
  "_raw_molarity_uxyjhtkqefcxbj-uhfffaoysa-n" float8,
  "_raw_molarity_uzhwwthdrvlcju-uhfffaoysa-n" float8,
  "_raw_molarity_vawhfunjdmqusb-uhfffaoysa-n" float8,
  "_raw_molarity_vmlaegaahiiwjx-uhfffaoysa-n" float8,
  "_raw_molarity_vnaauntyionohr-uhfffaoysa-n" float8,
  "_raw_molarity_wgyrinythsorgh-uhfffaoysa-n" float8,
  "_raw_molarity_xfyiczoiwsbqsk-uhfffaoysa-n" float8,
  "_raw_molarity_xqprbtxuxxvtkb-uhfffaoysa-m" float8,
  "_raw_molarity_xzucbfluebdnsj-uhfffaoysa-n" float8,
  "_raw_molarity_yejrwhavmiajkc-uhfffaoysa-n" float8,
  "_raw_molarity_ymwujeatgchhmb-uhfffaoysa-n" float8,  
  "_raw_molarity_yymlriwbiszomt-uhfffaoysa-n" float8,
  "_raw_molarity_zevrffcpaltvdn-uhfffaoysa-n" float8,
  "_raw_molarity_zmxddkwlczadiw-uhfffaoysa-n" float8,
  "_raw_molarity_iswnamnoyhctsb-uhfffaoysa-n" float8,
  "_raw_molarity_pnzdzrmobiiqtc-uhfffaoysa-n" float8,
  "_raw_molarity_qwangzftsgzrpz-uhfffaoysa-n" float8,
  "_raw_molarity_zaswjuomegbqcq-uhfffaoysa-l" float8,
  "_raw_molfraction_acid" float8,
  "_raw_molfraction_solvent" float8,
  "_raw_acid_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_inorganic_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_inorganic_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_organic_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_organic_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_solvent_0_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_solvent_1_inchikey" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_acid_0_smiles" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_acid_0_types" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_inorganic_0_br_count" int8, 
  "_raw_inorganic_0_cs_count" int8, 
  "_raw_inorganic_0_i_count" int8, 
  "_raw_inorganic_0_pb_count" int8, 
  "_raw_inorganic_0_atomic_electronegativity_br" float8,
  "_raw_inorganic_0_atomic_electronegativity_cs" float8,   
  "_raw_inorganic_0_atomic_electronegativity_i" float8,
  "_raw_inorganic_0_atomic_electronegativity_pb" float8,
  "_raw_inorganic_0_smiles" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_inorganic_0_types" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_inorganic_1_br_count" int8, 
  "_raw_inorganic_1_cs_count" int8, 
  "_raw_inorganic_1_i_count" int8, 
  "_raw_inorganic_1_pb_count" int8, 
  "_raw_inorganic_1_atomic_electronegativity_br" float8,
  "_raw_inorganic_1_atomic_electronegativity_cs" float8,   
  "_raw_inorganic_1_atomic_electronegativity_i" float8,
  "_raw_inorganic_1_atomic_electronegativity_pb" float8,
  "_raw_inorganic_1_smiles" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_inorganic_1_types" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_organic_0_smiles" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_organic_0_types" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_organic_1_smiles" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_organic_1_types" varchar(255) COLLATE "pg_catalog"."default",  
  "_raw_solvent_0_smiles" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_solvent_0_types" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_solvent_1_smiles" varchar(255) COLLATE "pg_catalog"."default",
  "_raw_solvent_1_types" varchar(255) COLLATE "pg_catalog"."default"
)
;
